### ISSUE TITLE
Figure out if we can easily pre-install flatpak apps

### ISSUE THREAD

**Issue by bhush9** [pinephone-project/planning-todos#3]
Some apps come as flatpak apps,

- PureMaps
- Spectral
- Telegram

See if we can easily pre-install them?

**Comment by star-buck** [comment]
Do these also exist as snaps?

Otherwise could we package e.g. puremaps as native?

**Comment by bhush9** [comment]
They are not available as snaps no, but some bits to consider,

- Due to involved dep tree, some apps are kind of hard to package
- Snaps can't work with our current testing device due to kernel version
- We already have them working as flatpaks, without much trouble, see telegram group for telegram and puremaps for example.

So for now I want to use them as-is for evaluation purpose and not spend limited time in packaging tasks, and think about packaging them natively or as-a-snap later when we run on properly mainlined hardware.

**Comment by star-buck** [comment]
How big is the same img with just puremaps flatpak + all necessary
underlying base flatpak compared to without any flatpak?

**Comment by bhush9** [comment]
I haven't actually tried this with pre-built or fresh image, but as estimate org.kde.Platform (provided by KDE) on which PureMaps, telegram, spectral and other Qt apps are depending should be roughly ~600 MB additional.

**Comment by bhush9** [comment]
Closing this issue since, edge image now ships two flatpaks. Telegram and PureMaps.
